# Generated by Django 2.2.3 on 2019-07-14 18:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import movies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(movies.models.current_year)])),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='MovieProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Person')),
            ],
            options={
                'verbose_name': 'MovieProducer',
                'verbose_name_plural': 'MovieProducers',
                'db_table': 'movie_producer',
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Person')),
            ],
            options={
                'verbose_name': 'MovieDirector',
                'verbose_name_plural': 'MovieDirectors',
                'db_table': 'movie_director',
            },
        ),
        migrations.CreateModel(
            name='MovieActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.Movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persons.Person')),
            ],
            options={
                'verbose_name': 'MovieActor',
                'verbose_name_plural': 'MovieActors',
                'db_table': 'movie_actor',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='casting',
            field=models.ManyToManyField(related_name='movies_as_actor', through='movies.MovieActor', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies_as_director', through='movies.MovieDirector', to='persons.Person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='producers',
            field=models.ManyToManyField(related_name='movies_as_producer', through='movies.MovieProducer', to='persons.Person'),
        ),
    ]
